export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col items-center px-4 py-12 bg-[#f8f5ef]">
      <div className="max-w-2xl w-full mx-auto">
        <h1 className="text-4xl md:text-5xl font-serif font-bold text-center mb-2">
          Ora – Terms of Service
        </h1>
        <div className="text-center text-lg md:text-xl mb-8 text-gray-700">
          Last updated: 6/5/2025
        </div>
        <div className="text-lg md:text-xl font-sans mb-8 text-gray-900">
          By using Ora, you agree to these terms.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">Purpose</h2>
        <div className="text-lg md:text-xl font-sans mb-6 text-gray-900">
          Ora is a tool designed to support personal prayer and spiritual growth
          through journaling, Scripture, and contemplative reflection.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">Eligibility</h2>
        <div className="text-lg md:text-xl font-sans mb-4 text-gray-900">
          You must be 13 years or older to use Ora. By using the app, you affirm
          that you meet this requirement.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">
          No Medical or Psychological Advice
        </h2>
        <div className="text-lg md:text-xl font-sans mb-6 text-gray-900">
          Ora provides <strong>spiritual encouragement</strong>, not medical,
          psychological, or professional counseling. Insights generated by AI
          are meant to support reflection, not replace pastoral care or therapy.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">
          AI Usage Disclaimer
        </h2>
        <div className="text-lg md:text-xl font-sans mb-6 text-gray-900">
          If you choose to use the AI feature, you understand and agree that
          your input will be sent to OpenAI. Ora is not responsible for the
          accuracy or theological soundness of AI-generated content. You use
          these insights at your discretion.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">
          Intellectual Property{" "}
        </h2>
        <div className="text-lg md:text-xl font-sans mb-6 text-gray-900">
          All content and designs in Ora are the intellectual property of the
          creator unless otherwise stated. You may not copy, resell, or
          reproduce the app's features without permission.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">
          Changes to Terms{" "}
        </h2>
        <div className="text-lg md:text-xl font-sans mb-6 text-gray-900">
          These terms may be updated occasionally. We will post the updated date
          at the top of this document. Continued use of Ora means you accept the
          current terms.
        </div>
        <h2 className="text-2xl font-serif font-bold mb-2">Contact</h2>
        <div className="text-lg md:text-xl font-sans mb-6 text-gray-900">
          For questions or support, email:{" "}
          <a
            href="mailto:soriano.jeffm@gmail.com"
            className="underline text-blue-700"
          >
            soriano.jeffm@gmail.com
          </a>
        </div>
      </div>
    </div>
  );
}
